# Supervised Learning

## Supervised Learning Algorithms

### Regression

### Linear Regression - One Variable

In [4]:
import pandas as pd
from pandas import DataFrame
from sklearn import linear_model
# Reading Data

data = pd.read_csv('multi_var_regression1.csv')
df = pd.DataFrame(data,columns=['Year','Month','Interest_Rate','Unemployment_Rate','Stock_Index_Price'])
X = df[['Interest_Rate']]# here we have 2 variables for multiple regression. If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.Alternatively, you may add additional variables within the brackets
Y = df['Stock_Index_Price']

# with sklearn
regr = linear_model.LinearRegression()
#verbose=1
regr.fit(X, Y)
print(regr.fit(X, Y))

print ('Intercept: \n', regr.intercept_)
print ('Coefficients: \n', regr.coef_)


# prediction with sklearn
#New_Interest_Rate = 2.75
#print(type(New_Interest_Rate))
# New_Unemployment_Rate = 5.3

New_Interest_Rate = float(input('Enter Interest Rate: '))
print ('Predicted Stock Index Price: \n', regr.predict([[New_Interest_Rate]]))


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)
Intercept: 
 -99.46431881371655
Coefficients: 
 [564.20389249]
Enter Interest Rate: 2.7
Predicted Stock Index Price: 
 [1423.88619092]


### Linear Regression - Multivariable

In [12]:
import pandas as pd
from pandas import DataFrame
from sklearn import linear_model


X = df[['Interest_Rate','Unemployment_Rate']] # here we have 2 variables for multiple regression. If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.Alternatively, you may add additional variables within the brackets
Y = df['Stock_Index_Price']
 
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)

print ('Intercept: \n', regr.intercept_)
print ('Coefficients: \n', regr.coef_)


# prediction with sklearn
# New_Interest_Rate = 2.75
# New_Unemployment_Rate = 5.3

New_Interest_Rate = float(input('Enter Interest Rate: '))
New_Unemployment_Rate = float(input('Enter Unemployment Rate: '))
print ('Predicted Stock Index Price: \n', regr.predict([[New_Interest_Rate ,New_Unemployment_Rate]]))

Intercept: 
 1798.4039776258546
Coefficients: 
 [ 345.54008701 -250.14657137]
Enter Interest Rate: 2.7
Enter Unemployment Rate: 5.3
Predicted Stock Index Price: 
 [1405.5853843]


### Logistic Regression Classification

In [25]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

# Uncomment while using manual input
# data = pd.read_csv('Iris.csv')
# X = data.drop(['Id', 'Species'], axis=1)
# y = data['Species']

# Comment while using manual input
X, y = load_iris(return_X_y=True)
clf = LogisticRegression()
clf.fit(X, y)

# Comment while using manual input
print (clf.predict(X[:2, :]))
print (clf.predict_proba(X[:2, :]))
print (clf.score(X, y))
y_pred = clf.predict(X)

# Uncomment while using manual input
# X = input('Enter values SepalLength SepalWidth PetalLength PetalWidth:')
# y_pred = clf.predict(X)
# print y_pred

[0 0]
[[8.78030305e-01 1.21958900e-01 1.07949250e-05]
 [7.97058292e-01 2.02911413e-01 3.02949242e-05]]
0.96


/home/vaishali/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vaishali/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


### Naive Bayes

In [22]:
from sklearn import datasets
iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(iris.data, iris.target)
#X = []
#X1 =(input('Enter values SepalLength SepalWidth PetalLength PetalWidth:').split())
X=[7.1,3,5.9,2.1]
#for item in X1:
#    X.append(float(item))
#print(X)
y_pred = gnb.predict([X])
#7.1,3,5.9,2.1
if y_pred==0:
    print ('Iris-setosa')
elif y_pred==1:
    print ('Iris-versicolor')
else:
    print ('Iris-virginica')

Iris-virginica


### Support Vector Machines (SVMs)

In [24]:
import numpy as np
from sklearn import svm

data = pd.read_csv('Iris1.csv')
X = data.drop(['Id', 'Species'], axis=1)
y = data['Species']

clf = svm.SVR()
clf.fit(X,y);
X=[7.1,3,5.9,2.1]
#X = input('Enter values SepalLength SepalWidth PetalLength PetalWidth:')
y_pred = clf.predict([X])

if 0<y_pred<10:
    print ('Iris-setosa')
elif 10<y_pred<20:
    print ('Iris-versicolor')
else:
    print ('Iris-virginica')
        

[20.50942546]
Iris-virginica


/home/vaishali/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


### Decision Trees 

## Decision Trees in Machine Learning
### A tree has many analogies in real life, and turns out that it has influenced a wide area of machine learning, covering both classification and regression. In decision analysis, a decision tree can be used to visually and explicitly represent decisions and decision making.

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=0)
iris = load_iris()

cross_val_score(clf, iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])