# Numpy

## Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays

## Basics 

In [1]:
list1=[3,4,5]
print(list1)

[3, 4, 5]


In [1]:
import numpy as np

In [2]:
arr=np.arange(6)
%time print(arr)

[0 1 2 3 4 5]
Wall time: 997 µs


In [3]:
list2=list(range(6))

In [4]:
%time print(list2)

[0, 1, 2, 3, 4, 5]
Wall time: 0 ns


In [5]:
array1=np.array([3,2,5,1])  #1D array
array1

array([3, 2, 5, 1])

In [6]:
print(type(array1))

<class 'numpy.ndarray'>


In [7]:
array1.shape

(4,)

In [8]:
array2=np.array([[3,2,5,8,1],[3,2,5,3,10]])  #2D array
array2

array([[ 3,  2,  5,  8,  1],
       [ 3,  2,  5,  3, 10]])

In [9]:
array2.shape

(2, 5)

In [10]:
array2.dtype

dtype('int32')

## Creating Blank Arrays

In [11]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros(6).dtype

dtype('float64')

In [16]:
arr1=np.array([[3,2,5,1],[2,4,5,6]])
arr1

array([[3, 2, 5, 1],
       [2, 4, 5, 6]])

In [17]:
arr2=np.array([[2,3,5,6],[6,4,4,6]])
arr2

array([[2, 3, 5, 6],
       [6, 4, 4, 6]])

## Arithmetic Operations 

In [18]:
arr1+arr2

array([[ 5,  5, 10,  7],
       [ 8,  8,  9, 12]])

In [19]:
arr1-arr2

array([[ 1, -1,  0, -5],
       [-4,  0,  1,  0]])

In [20]:
arr1*arr2

array([[ 6,  6, 25,  6],
       [12, 16, 20, 36]])

In [21]:
arr1/arr2

array([[1.5       , 0.66666667, 1.        , 0.16666667],
       [0.33333333, 1.        , 1.25      , 1.        ]])

In [22]:
arr1//arr2

array([[1, 0, 1, 0],
       [0, 1, 1, 1]], dtype=int32)

## Array Slicing

In [23]:
ar1=np.array([5,4,5,6,6,7,8,2])

In [24]:
ar2=ar1[4:6]

In [25]:
ar2

array([6, 7])

## Dot Product and Cross Product

In [26]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

# Matrix Multiplication

In [27]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [28]:
np.dot(A, B)                # another matrix product

array([[5, 4],
       [3, 4]])

In [29]:
np.cross(A, B)

array([-2, -3])